### ISSUE TITLE
[PE-D] Time attribute not explained in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-2/tp#228] opened 2021-10-30 17:22 UTC
The time attribute that can be set is not adequately explained in the UG.  
It is specified that it needs to be two integers separated by a comma, but does not explain what the two integers represent. 

![image.png](https://raw.githubusercontent.com/JMattChiam/ped/main/files/dd113e29-ab5c-4342-b1be-441a74aad39d.png)

-------------
Labels: `severity.High` `type.DocumentationBug`
original: JMattChiam/ped#6

**Comment by ChuaXiongWei** [comment] 2021-10-31 06:40
Duplicate of issue #247

**Closed by ChuaXiongWei** 2021-10-31 06:40 UTC
